DROP TABLE IF EXISTS missions;
 
CREATE TABLE missions (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  primaryWeapon VARCHAR(250) NOT NULL,
  secondaryWeapon VARCHAR(250) DEFAULT NULL,
  hero VARCHAR(250) DEFAULT NULL
);