DROP TABLE IF EXISTS missions;
 
CREATE TABLE missions (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  title VARCHAR(250) NOT NULL,
  weapon1 VARCHAR(250) NOT NULL,
  weapon2 VARCHAR(250) DEFAULT NULL,
  hero VARCHAR(250) DEFAULT NULL
);